#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# PANTALLAS
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d 11 12 13 14

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# FONDO PANTALLA
/usr/bin/feh --bg-fill /home/pylon/Documents/Wallpapers/1.jpg &

# POLYBAR
~/.config/polybar/launch.sh

# PICOM
picom --config ~/.config/picom/picom.conf &
bspc config border_width 2
